export const ACCESS_TOKEN = 'ACCESS-TOKEN' // 用户token
export const CURRENT_USER = 'CURRENT-USER' // 当前用户信息
export const DESIGN_SETTING = 'DESIGN-SETTING' // 当前用户主题信息

export const PREDICT_RESULTS = 'PREDICT-RESULTS'
export const PREDICT_RESULTS_SC = 'PREDICT-RESULTS-SC'
export const PREDICT_RESULTS_MPHNSYN = 'PREDICT-RESULTS-MPHNSyn'
export const PREDICT_RESULTS_MPHNSYN_Target = 'PREDICT-RESULTS-MPHNSyn-TARGET'