/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AlgorithmIntro: typeof import('./../components/AlgorithmIntro/index.vue')['default']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    AResult: typeof import('ant-design-vue/es')['Result']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASkeletonImage: typeof import('ant-design-vue/es')['SkeletonImage']
    ATable: typeof import('ant-design-vue/es')['Table']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    CardTitle: typeof import('./../components/Login/CardTitle.vue')['default']
    HappyButton: typeof import('./../components/HappyButton/index.vue')['default']
    Login: typeof import('./../components/Login/index.vue')['default']
    LoginCard: typeof import('./../components/Login/LoginCard.vue')['default']
    Profile: typeof import('./../components/Profile/index.vue')['default']
    RegisterCard: typeof import('./../components/Login/RegisterCard.vue')['default']
    Result: typeof import('./../components/Login/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./../components/Sider/index.vue')['default']
    SinglePredictResult: typeof import('./../components/SinglePredictResult/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    SvgImage: typeof import('./../components/SvgImage/index.vue')['default']
    TopNavBar: typeof import('./../components/TopNavBar/index.vue')['default']
    UserNavMenu: typeof import('./../components/UserNavMenu/index.vue')['default']
  }
}
